package com.asher_stern.crf.postagging.data.penn;

import java.util.LinkedList;
import java.util.List;
import java.util.Stack;

import com.asher_stern.crf.utilities.CrfException;

/**
 * Parses an ".mrg" file of Penn Tree-Bank, and generates a Java data-structure for each parse-tree.
 * 
 * 
 * @author Asher Stern
 * Date: Nov 16, 2014
 *
 */
public class PennFileContentsParser
{
	/**
	 * Constructor with the contents of the ".mrg" file. 
	 * @param contents The contents of the ".mrg" file. This char array is typically generated by String.toCharArray().
	 */
	public PennFileContentsParser(char[] contents)
	{
		super();
		this.contents = contents;
	}
	
	
	/**
	 * Parses the contents of the ".mrg" file.
	 */
	public void parse()
	{
		StringBuilder activeNodeContent = null;
		for (int index=0;index<contents.length;++index)
		{
			char c = contents[index];
			if (Character.isWhitespace(c))
			{
				if (activeNodeContent!=null)
				{
					activeNodeContent.append(c);
				}
			}
			else if (c=='(')
			{
				if (activeNodeContent!=null)
				{
					PennParserTreeNode node = new PennParserTreeNode(activeNodeContent.toString());
					if (!activeStack.isEmpty())
					{
						activeStack.peek().addChild(node);
					}
					activeStack.push(node);
				}
				activeNodeContent = new StringBuilder();
			}
			else if (c==')')
			{
				if (activeNodeContent!=null)
				{
					PennParserTreeNode node = new PennParserTreeNode(activeNodeContent.toString());
					if (!activeStack.isEmpty())
					{
						activeStack.peek().addChild(node);
					}
					activeStack.push(node);
				}
				PennParserTreeNode poped = activeStack.pop();
				if (activeStack.isEmpty())
				{
					trees.add(poped);
				}
				activeNodeContent = null;
			}
			else
			{
				if (activeNodeContent==null) {throw new CrfException("Malformed PTB file contents.");}
				activeNodeContent.append(c);
			}
		}
	}
	
	

	/**
	 * Returns the list of parse-trees. The list contains the root node of each parse-tree.
	 * @return
	 */
	public List<PennParserTreeNode> getTrees()
	{
		return trees;
	}



	private final char[] contents;
	
	private Stack<PennParserTreeNode> activeStack = new Stack<PennParserTreeNode>();
	private List<PennParserTreeNode> trees = new LinkedList<PennParserTreeNode>();
}
